name: Build simpleserver
on: [push, pull_request]
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
     with:
      fetch-depth: 1
   - name: update packages
     run: sudo apt update
   - name: Install required and optional dependencies
     run: >
      sudo apt install perl gcc make libyaz-dev pkg-config
   - name: Generate Makefile
     run: perl Makefile.PL
   - name: Run make test
     run: make test
